### PR TITLE
File list component

### PR DESCRIPTION
**Pull request by KovaCro**

### CODE REVIEW

**Comment by KovaCro** [comment]
@flauc All files get attached to a single `<input type="file">` so I didn't implement `save()` since form can handle it as it would handle any other `<input type="file">`. 

Should I make it the same as the file upload is? The internal value being the JSON string of an array of links to files that the service saves when `save()` is called.

**Comment by flauc** [comment]
@KovaCro yes please and the component should be able to handle an initial value as well in the form of a list of urls. An additional problem here is what happens when you remove something from an already existing document. Ideally save should get something like this `{added: FileList, removed: string[]}`

**Comment by KovaCro** [comment]
@flauc It can handle initial value in the form of URLs. Dispatches event with URL as detail if the saved file is removed so the form can handle that externally through the service. Saves unsaved files with save() and adds URLs to value. Did not add an upload button but added dispatch on change with a number of unsaved files as detail so the button can be added externally.

**Comment by flauc** [comment]
@KovaCro sounds good to me, feel free to merge this.

**Pull request merged**
